const date = [
{
store_no:"001",
name:"幸せや(今渡店)",
key:['和食','とんかつ',],
place:'可児市',
commnet:'やわらかとんかつ！',
detail_img:1,
detail_text:"岐阜県内に3店舗あってとても綺麗で落ち着いた雰囲気のお店！\nやわらかとんかつの名の通りお肉がとっても柔らかくて美味しい😋なんとこの値段でキャベツ、ご飯、お味噌汁がおかわり自由！！幸せになれるトンカツを食べに是非是非行ってみてね😆",
detail_address:'岐阜県可児市今渡1271-1',
detail_holiday:'無し',
detail_hours:'11:00-14:30 17:00-21:00',
detail_parking:'約18台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOYJ5boAalf/?igsh=cWM2ZzhxeXJ4eGE1',
detail_map:'https://maps.app.goo.gl/7kvN2FXEjRuEMntt6',
},
{
store_no:"001",
name:"食道　やま",
key:['和食',],
place:'関市',
commnet:'幸せ〜がいっぱい詰まった生姜焼き！',
detail_img:1,
detail_text:"関市にある『食道 やま』に行って来たよ🍚\n幸せ〜がいっぱい詰まった生姜焼き！トンテキかと思うくらいの厚みのあるお肉が二枚重なって甘辛いタレの照り✨\n店内に広がるいい香り！ひと口食べれば柔らかいお肉の旨味が口いっぱいに広がって幸せを感じる美味さ！\n添えられた野菜もシャキシャキの青梗菜に柔らかい茄子がお肉とあう😋\nお店の場所は少しわかりにくい所にあるよ！\n食事の提供時間は少しかかるので時間にゆとりを持って行ってね！\n大満足の生姜焼き定食是非是非行ってみてね☺️",
detail_address:'岐阜県関市下有知187',
detail_holiday:'火・水曜日',
detail_hours:'11:30-14:00 17:30-20:00',
detail_parking:'約10台',
detail_url_shop:'https://www.instagram.com/yamagohan.eating?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DS8k93Yk47S/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/abEtf8MnQiAuLaLd7',
},
{
store_no:"001",
name:"マルシゲ鉄板堂",
key:['和食','居酒屋',],
place:'岐南町',
commnet:'昭和レトロな空間はどこか落ち着く雰囲気！',
detail_img:1,
detail_text:"羽島郡岐南町にある鉄板焼き居酒屋『マルシゲ鉄板堂』に行ってきたよ😊ネギ畑の中にあって、昭和レトロな空間はどこか落ち着く雰囲気😌鉄板焼きメニューも豊富でマルシゲさんの看板メニュースジコンねぎ焼きなど岐南町徳田名物の徳田ねぎをふんだんに使用した料理が味わえるお店！鉄板調理が目の前で見られる特等席のカウンターもオススメ！美味しい鉄板料理にお酒もバッチリ合うから是非是非行ってみてね☺️",
detail_address:'岐阜県羽島郡岐南町徳田西4-80',
detail_holiday:'日曜日',
detail_hours:'17:00 - 23:00 L.O. 22:00',
detail_parking:'約13台',
detail_url_shop:'https://www.instagram.com/marushige_teppandou/',
detail_url_link:'https://www.instagram.com/reel/DRB5Va3Af1g/?igsh=NjU0dHM5c20zZDZ1',
detail_map:'https://maps.app.goo.gl/5zix13wi1PXAv87J9',
},
{
store_no:"001",
name:"Cafe & Rest TAKU",
key:['カフェ',],
place:'各務原市',
commnet:'コスパ抜群のフライランチ定食！',
detail_img:1,
detail_text:"各務原にある『Cafe & Rest TAKU』に行ってきたよ☕️コスパ抜群のフライランチ定食が食べられる地元に愛される老舗喫茶店！お値打ちなランチメニューが豊富！オーダーしてから料理が提供される時間が早いのが驚き！フライはサックサク唐揚げもガリっと音が出るほど焼きそばは熱々の鉄板でこれまた凄いボリューム\n焼きそばの下にたまごが敷かれているスタイル☺️コスパ、ボリューム、味が最高で見た目のインパクトも凄いフライ定食を食べに是非是非行ってみてね😊",
detail_address:'岐阜県各務原市蘇原栄町2-29',
detail_holiday:'日曜日',
detail_hours:'7:00-14:00',
detail_parking:'約12台',
detail_url_shop:'https://www.instagram.com/caferesttaku?igsh=M2c2NGRsNDdjM21o',
detail_url_link:'https://www.instagram.com/reel/DQ0Cbi2E94b/?igsh=cHJuN3VuY2FpaWdv',
detail_map:'https://maps.app.goo.gl/87ovRaRBuzoW5ofv8',
},
{
store_no:"001",
name:"DA ACHIU",
key:['洋食',],
place:'岐阜市',
commnet:'ナポリピッツァ協会認定のお店で、岐阜でピザと言えばココ！',
detail_img:1,
detail_text:"岐阜駅から徒歩５分以内で好立地のイタリアン料理店『Pizzeria e trattoria DA ACHIU』に行って来たよ☺️2019年にミシュランビブグルマン獲得！食べログ評価『3.78』全国ピザ食べログランキング11位2017年、2019年、2021年、2023年、2025年と百名店に選出された名店！ナポリピッツァ協会認定のお店で、岐阜でピザと言えばココ！豚の甘みがたまらない絶品ハムに自家製パンチェッタコッタ・コッタ・ドルチェをたっぷりと乗せ、さらに水牛チーズ、カチョカヴァロ、燻製チーズ、モッツァレラチーズ、パルミジャーノ・レッジャーノを合わせた絶品ピザ！お酒の種類やピザの品数が多く色々な種類の料理を楽しめる！味はもちろん丁寧な心遣いなどの接客も良かったよ！注文に迷ったらまずファラリーニ！岐阜NO.1のピザを食べに是非是非行ってみてね☺️",
detail_address:'住所岐阜県岐阜市神田町7-17 神田ビル 1F',
detail_holiday:'月曜日',
detail_hours:'11:30-14:00 17:30-21:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DQxTZnqk5Si/?igsh=ajN5aHA2c2lyYncx',
detail_map:'https://maps.app.goo.gl/eNvk5fh7LFyREvcq9',
},
{
store_no:"002",
name:"神戸クック・ワールドビュッフェ",
key:['和食','中華','洋食',],
place:'各務原市',
commnet:'世界の料理が楽しめる食べ放題のお店！',
detail_img:1,
detail_text:"各務原にある食べ放題のお店『神戸クック・ワールドビュッフェ イオンタウン各務原鵜沼店』に行ってきたよ☺️世界の料理が楽しめるカフェ&ビュッフェレストランで100種類以上のメニューが時間無制限で食べ放題！",
detail_address:'岐阜県各務原市鵜沼西町3-309',
detail_holiday:'無し',
detail_hours:'11:00-15:30 17:00-21:30',
detail_parking:'有り',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRGWvPegQf2/?igsh=ZmN4NTgxdXVrYzh4',
detail_map:'https://maps.app.goo.gl/V92rXmVUwZ2Yx1zw6',
},
{
store_no:"002",
name:"一柳商店",
key:['焼肉','和食',],
place:'岐南町',
commnet:'110種類以上のメニューが食べ放題の焼肉屋さん！',
detail_img:1,
detail_text:"羽島郡岐南町にある焼き肉食べ放題のお店『一柳商店』に行ってきたよ🥩\n110種類以上のメニューが食べ放題でサイドメニューも豊富！焼肉だけでなくお好み焼きからデザートまで味良し！コスパ良し！の食べ放題😋食べ放題時間は100分（ラストオーダー30分前）だよ！ホットペッパークーポンを使えば下記値段で楽しめるからオススメ！（現金払いのみ）平日でも混雑している人気店！週末は行くなら3日以上前に予約していくのがオススメ！色んなメニューがお腹いっぱい食べれるから是非是非行ってみてね☺️",
detail_address:'岐阜県羽島郡岐南町上印食6-76',
detail_holiday:'無し',
detail_hours:'17:00-23:00(土日以外)16:00-23:00(土日)',
detail_parking:'約13台',
detail_url_shop:'https://www.instagram.com/ichiyanagishouten_ibs/',
detail_url_link:'https://www.instagram.com/reel/DQfkIm-EiRx/?igsh=bWoxeGN3N2lzdzgx',
detail_map:'https://maps.app.goo.gl/2gzA9Bcy3hhDxdTYA',
},
{
store_no:"002",
name:"horikajitsukobo",
key:['カフェ',],
place:'岐阜市',
commnet:'旬の果物を使ったカフェ！',
detail_img:1,
detail_text:"創業50年の老舗フルーツ店「フルーツHORI」がはじめたカフェ『horikajitsukobo』に行ってきたよ☺️店内でジュースやパフェを食べるのもヨシ！大切な人への手土産にもヨシ！！2019年6月18日オープンの創業50年の果実店『フルーツHORI」の店主が「旬の果物を気軽に味わってほしい」と始めたカフェで、全国各地のフルーツを使ったパフェやジュースなどが味わえる。その時に一番美味しい果物を厳選し、完熟した果物だけを使用！甘さすっきりの生クリームを地元のパン屋に特注する柔らかな食パンでサンドしたフルーツサンドはどれも絶品！パフェは間違いなく美味しいし、手土産にも喜ばれるから是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市茜部本郷1-30-30',
detail_holiday:'水・木曜日',
detail_hours:'12:00-18:00',
detail_parking:'約5台',
detail_url_shop:'https://www.instagram.com/horikajitsukobo/',
detail_url_link:'https://www.instagram.com/reel/DQbphpvgdyo/?igsh=bHVnYjU5Ynp2ZzZ1',
detail_map:'https://maps.app.goo.gl/YK54eWUqht3X1TEA8',
},
{
store_no:"003",
name:"Elefans' Café&BAL",
key:['カフェ','洋食',],
place:'岐南町',
commnet:'人気ハウスメーカーが手掛けるオシャレカフェ！',
detail_img:1,
detail_text:"岐阜県岐南町にある人気ハウスメーカーさんが手掛けるオシャレカフェ『Elefans' Cafe&BAL』に行ってきたよ☺️2025年9月14日開催の「ぎふモーニングプロジェクト」のぎふ健康モーニング、プレミアムモーニング部門で優勝したお店🏆店内は綺麗で広々としていて、お子様連れにも優しい空間！テーブル席とソファー席に加えてキッズスペースもあるから小さいお子様も大満足👦焼き立ての自家製のパンが味わえて、水とアセロラ水がセルフサービスで飲めるよ！ランチは全メニューにデザート、ドリンク付き!バターチキンカレー、ふわとろオムライス以外のランチにはサラダ、スープ、五穀米or手作り食パン付きと豪華！！フリーWifiや配膳ロボット完備！ランチ限定でお店のインスタフォロー画面提示で100円オフ！人気店なのでスムーズに入店したい方は予約がオススメだよ！モーニング、ランチ、ディナーまで楽しめるから是非是非行ってみてね☺️",
detail_address:'岐阜県羽島郡岐南町三宅4丁目242',
detail_holiday:'木曜日',
detail_hours:'9:00-15:00',
detail_parking:'約5台',
detail_url_shop:'https://www.instagram.com/elefanscafe/',
detail_url_link:'https://www.instagram.com/reel/DQZIGG1AQJU/?igsh=MWtsdW53YmM4M3ZkOQ%3D%3D',
detail_map:'https://maps.app.goo.gl/vXAupUEbMmw1diFp9',
},
{
store_no:"003",
name:"ベトコンラーメン三條",
key:['ラーメン',],
place:'岐阜市',
commnet:'岐阜に4店舗！人気のベトコンラーメン店！',
detail_img:1,
detail_text:"岐阜県岐阜市柳津にある人気ラーメン店『ベトコンラーメン 三條』に行ってきたよ😆カラフルタウンからすぐ近くの所にあって『スタミナ入れてください』の赤い看板が目印のお店！ベトコンとはベストコンデションの略でスタミナ注入で食べたらベストコンディションになれるってこと💪駐車場からにんにくの香りがしてきて、店内に入ると煙がモクモクと昔ながらのらーめん屋さんで雰囲気抜群の店内！あっさりした醤油ベースのスープに、ニラ、もやし、ホクホクのにんにくがゴロゴロ入ってる🧄ニンニクの香ばしさはそのままで、シツコい臭いや辛みなどは一切なく見た目よりもサラッと食べられる一杯でビールにもよく合う🍻カウンター席と4人掛けテーブル席が配置されてたよ🪑ベストコンディションになれるラーメンを食べに是非是非行ってみてね🍜",
detail_address:'岐阜市柳津町南塚4-237',
detail_holiday:'無し',
detail_hours:'11:00-23:00',
detail_parking:'約14台',
detail_url_shop:'https://www.instagram.com/betokon_sanjyo01/?igsh=MTB1ZnI1cnpyYW5tOA%3D%3D#',
detail_url_link:'https://www.instagram.com/reel/DQNNiN3k1dy/?igsh=Ynd1bGJ3bmt0NTFk',
detail_map:'https://maps.app.goo.gl/qtRA76YjKM5fZRBp6',
},
{
store_no:"004",
name:"お気軽しゃぶしゃぶ　えびす　本店",
key:['しゃぶしゃぶ','和食',],
place:'岐阜市',
commnet:'定番スタイルで楽しめる新感覚のしゃぶしゃぶ屋さん！',
detail_img:1,
detail_text:"2025年4月3日岐阜県岐阜市柳津にNewOpenしたしゃぶしゃぶ屋さん『お気軽しゃぶしゃぶ えびす 本店』に行って来たよ☺️定食スタイルで楽しめる新感覚のしゃぶしゃぶ屋さんで家族、友人、一人でも気軽に楽しめるのが魅力！厳選された国産牛や豚肉、新鮮な野菜がボリューム満点のしゃぶしゃぶセットは税込1,078円～とコスパも抜群！店内は明るく清潔感のある落ち着いた雰囲気でみんなでも1人でも気軽に行けるから是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市柳津町蓮池5-5-5',
detail_holiday:'無し',
detail_hours:'11:00-22:30',
detail_parking:'約30台',
detail_url_shop:'https://www.instagram.com/shabushabu_ebisu/?igsh=MXZlbGdueTIweWE0ag%3D%3D#',
detail_url_link:'https://www.instagram.com/reel/DQGsce4AWwh/?igsh=MW14NGR4MzRoZTBxcQ%3D%3D',
detail_map:'https://maps.app.goo.gl/asiqmgBHAUw2LXUr9',
},
{
store_no:"001",
name:"韓のあじ家",
key:['チゲ鍋','韓国料理',],
place:'本巣市',
commnet:'本格的な韓国料理！',
detail_img:1,
detail_text:"本巣郡北方町にある『韓のあじ家』に行って来たよ🇰🇷岐阜市にあった韓国チゲ鍋店が本巣郡北方町に8/27復活移転オープン！有名ケーキ屋さんフランボワーズの裏にあるよ！本格的な韓国料理が食べれるお店で前菜プレートがついたランチがお得😆ホルモンのチゲはホルモン出汁とキムチの程よい辛さのスープが美味しい😋ホルモンはプルプルでお豆腐と白菜キムチが入ってるよ！プルコギ石焼ビビンパは辛味噌と生たまごを混ぜ合わせておこげが美味しい☺️辛さも控えめで食べやすい！新しい店内で座席もゆったり座れておすすめなので是非是非行ってみてね☺️",
detail_address:'本巣郡北方町高屋清流5-19',
detail_holiday:'無し',
detail_hours:'11:00-15:00 17:30-22:00(月・木・金・土・日曜日)',
detail_parking:'約10台',
detail_url_shop:'https://www.instagram.com/kannoaziya/',
detail_url_link:'https://www.instagram.com/reel/DPuUXxhk-0q/?igsh=MWY3ZjlpbDIxY2Q4Zg%3D%3D',
detail_map:'https://maps.app.goo.gl/dCvai5t6p6zBgMQs8',
},
{
store_no:"003",
name:"オレンジピール",
key:['洋食',],
place:'各務原市',
commnet:'欲張りワンプレートがおすすめ！',
detail_img:1,
detail_text:"各務原市にある人気洋食屋さん『オレンジピール』に行ってきたよ☺️いちょう通り沿いにあって、モーニングからランチ、ディナーまで楽しめるお店☕️オムライスとハンバーグやハンバーグと唐揚げがワンプレートになった欲張りワンプレートがおすすめ！オムライスはトロトロたまごに包まれてて、ハンバーグもフワフワジューシーで美味しい😆オムライスドリアも熱々のチーズがトロトロでこれまた絶品！食後のコーヒーもデザートも美味しかったよ🍨当日予約の電話はモーニングタイムのみ（8:30～11:00）翌日以降の予約はInstagramのDMでも可能だよ😊おすすめなので是非是非行ってみてね！",
detail_address:'岐阜県各務原市那加不動丘2-115',
detail_holiday:'火・水・金曜日',
detail_hours:'11:30-14:00 17:30-20:00(木曜日)',
detail_parking:'約14台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DPr1WTkk7pY/?igsh=MWNhczdqM2J4cXAxag%3D%3D',
detail_map:'https://maps.app.goo.gl/fmqwfG3QZsNf6dqf8',
},
{
store_no:"005",
name:"飯処　雲隠レ",
key:['居酒屋','和食',],
place:'岐阜市',
commnet:'オシャレで明るい店内と創作料理やお酒のメニューが豊富な居酒屋！',
detail_img:1,
detail_text:"岐阜駅から徒歩数分の玉宮に2025年7月1日にNewOpenした居酒屋さん『飯処 雲隠レ』に行って来たよ😊 オシャレで明るい店内と創作料理やお酒のメニューが豊富🍻レバニラは店員さんが作ってくれたり、釜飯もよそってくれたりで元気な店員さんの接客が良かったよ😆ホットペッパークーポンで毎週土日の昼のみと日～木曜日限定で何杯飲んでも生ビール299円+税 ハイボール199円+税も魅力的！映えてて美味しい本格居酒屋さんに是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市玉宮町1-20m.clues1F',
detail_holiday:'無し',
detail_hours:'16:00-1:00 12:00-1:00(土・日曜日)',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DPnzkUfASGs/?igsh=bGc5MjVkd2k5NTJ3',
detail_map:'https://maps.app.goo.gl/JZEj29xVm3idwmqbA',
},
{
store_no:"006",
name:"名古屋辛麺 鯱輪 長良店",
key:['ラーメン',],
place:'岐阜市',
commnet:'旨辛にんにくラーメンが絶品！',
detail_img:1,
detail_text:"9月27日岐阜県岐阜市にNewOpenした名古屋の人気ラーメン店『名古屋辛麺 鯱輪 長良店』に行って来たよ☺️岐阜県初出店で東海地区では栄、熱田、岡崎、今池に続く5店舗目😆店員さんの対応は明るく丁寧で外観、店内、はし、レンゲ、お水のコップの色までも真っ赤に統一さてれた😆Openしたばかりの人気店だから当分混雑は予想されるけど、食べログ辛麺カテゴリ全国1位の旨辛ラーメンを食べに是非是非行ってみてね😊",
detail_address:'岐阜県岐阜市下土居２丁目25-10',
detail_holiday:'火曜日',
detail_hours:'11:00-15:00 18:00-22:00',
detail_parking:'約16台',
detail_url_shop:'https://www.instagram.com/shachirin_gifunagara/',
detail_url_link:'https://www.instagram.com/reel/DPXwfhdAehc/?igsh=MWRyZnFxY25oZDBxeg%3D%3D',
detail_map:'https://maps.app.goo.gl/MgAXaNkBjXvEqCBh9',
},
{
store_no:"007",
name:"ひとめぼれ　岐阜駅前店",
key:['居酒屋','和食',],
place:'岐阜市',
commnet:'コスパ最強居酒屋！',
detail_img:1,
detail_text:"名古屋でエリア拡大中の人気店が9/19に岐阜初上陸！！コスパ最強居酒屋『ひとめぼれ 岐阜駅前店』に行ってきたよ🍻関西発のコスパ最強居酒屋でなんと飲み放題が衝撃の1時間550円（税込）！！餃子や焼き鳥などの定番メニュー全130種2時間食べ飲み放題が2,500円（税込）～など赤字覚悟の料金設定！とりあえずの1軒目、2軒目や、お茶漬けやラーメン、デザートなど〆の3軒目にもGOOD👌とにかくコスパが良くて、メニューも豊富で明るく活気があるお店だから是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市神田町9-15 トリタビル B1F',
detail_holiday:'無し',
detail_hours:'17:00-23:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:'https://www.instagram.com/hitomebore.gifuekimae/',
detail_url_link:'https://www.instagram.com/reel/DPXYCPdAaWd/?igsh=MWtrNzk0ZGFoMHFraw%3D%3D',
detail_map:'https://maps.app.goo.gl/K4nuuNWbDXxKSd7D8',
},
{
store_no:"008",
name:"糸　岐阜六条店",
key:['和食',],
place:'岐阜市',
commnet:'生姜料理といえばこのお店！',
detail_img:1,
detail_text:"岐阜市六条にある和食屋さん『生姜の仕合わせ 糸』に行ってきたよ🫚えらべるランチはメイン10種類より２つ選択できて「生姜鍋」「生姜ご飯」「デザート」「惣菜1品」「珈琲」も付いた豪華なランチセット☺️おかずはどれも生姜ごはんとの相性抜群で納得のボリュームとコスパだからリピート間違いなし！！他では味わえない「生姜」がコンセプトの和食屋さんに是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市六条南3-4-2',
detail_holiday:'月曜日',
detail_hours:'11:00-14:30',
detail_parking:'約14台',
detail_url_shop:'https://www.instagram.com/itoooooo8/',
detail_url_link:'https://www.instagram.com/reel/DPCpAQQEz3c/?igsh=ZzMzOTByOGw3ZnY3',
detail_map:'https://maps.app.goo.gl/6QKcsMWmQsAYs6PX8',
},
{
store_no:"009",
name:"お好み焼き本舗（柳津店）",
key:['和食',],
place:'岐阜市',
commnet:'お好み焼きといえばこのお店！',
detail_img:1,
detail_text:"岐阜市柳津にある食べ放題コースが充実の『お好み焼き本舗』に行ってきたよ☺️岐阜県に1店舗、愛知県に5店舗を展開！単品オーダーも可能だけどコスパの良い食べ放題コースがオススメ🙆食べ放題メニューは全4種類で時間は100分制（ラストオーダー20分前）※幼児無料で小学生は半額今回はお手軽コースを注文！衝撃だったのは数量限定のアップルパイもんじゃの熱冷スイーツ🍨店員さんがかけてくれるマヨビームも必見！他にも平日限定の（15時まで）ランチセットメニューも税込979円からあるよ！毎月20日はおこほんの日で10%割引とスタンプ5倍の特典あり🉐アプリ取得してクーポン使用も良さそう！週末は混むから予約必須！メニューも豊富で色んな種類がたくさん食べれるから是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市柳津町本郷4-1-33',
detail_holiday:'無し',
detail_hours:'11:00-23:00(月・土・日曜日) 17:00-23:00(火・水・木・金曜日)',
detail_parking:'約20台',
detail_url_shop:'https://www.instagram.com/okonomiyaki_honpo_official/',
detail_url_link:'https://www.instagram.com/reel/DPABKuBk15h/?igsh=d2JzYXRxOXZ6NDV1',
detail_map:'https://maps.app.goo.gl/VQNUuCHpnrSCPhCY6',
},
{
store_no:"002",
name:"pasteria JIJI",
key:['洋食',],
place:'本巣市',
commnet:'パスタとイタリア料理のお店！',
detail_img:1,
detail_text:"本巣郡北方町にあるパスタとイタリア料理のお店『pasteria JIJI』 に行ってきたよ🍝絶品パスタをお値打ちにいただける人気店でランチはサラダ・パン・パスタ・デザートがつくよ☺️サラダは新鮮シャキシャキでドレッシングが美味しい！パンはなんとおかわり自由🥖お店は駐車場から少し離れた場所にあって横断歩道を渡るから子ども連れの方は注意してね😊パスタは野菜の旨みをいかした本格的な味でコスパもいいので是非是非行ってみてね😆",
detail_address:'岐阜県本巣郡北方町北方1908-1',
detail_holiday:'日曜日',
detail_hours:'11:00-14:30',
detail_parking:'約10台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DO9irPVkyjv/?igsh=MTduajlqazBsY3Q3aw%3D%3D',
detail_map:'https://maps.app.goo.gl/HgxeAkJVQ2uqBYZ37',
},
{
store_no:"001",
name:"焼肉むらちゃん",
key:['焼肉','和食',],
place:'安八町',
commnet:'味とコスパ最強の焼肉店！',
detail_img:1,
detail_text:"安八町にある、味とコスパ最強の焼肉店『焼肉むらちゃん』に行って来たよ🥩地元の人に愛されるお店で、知る人ぞ知る穴場の焼肉店☺️A5ランクの飛騨牛や海鮮、ご飯物までメニューも豊富で美味しいお肉がリーズナブルに食べられるよ！薄切りのネギ塩牛タンは薄切りで食べやすく何枚でもいけちゃうし、ロースはほどよい霜降りと赤身の旨味のバランスが良く、相性抜群のタレをつけたらご飯が進むこと間違いなし🍚行ったら注文必須だよ！知る人ぞ知る味よしコスパよしの焼肉店に是非是非行ってみてね😆",
detail_address:'岐阜県安八郡安八町森部1751-1',
detail_holiday:'火曜日',
detail_hours:'17:00-22:00',
detail_parking:'約10台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DO65Cp4E89y/?igsh=MWlwNG81anM2cjVxMw%3D%3D',
detail_map:'https://maps.app.goo.gl/z2HeU1a2joK66img9',
},
{
store_no:"010",
name:"田毎（たごと）",
key:['和食','うどん',],
place:'岐阜市',
commnet:'行列のできる老舗麺処！',
detail_img:1,
detail_text:"岐阜市日置江にある手打ちうどん、そばの『田毎（たごと）』に行ってきたよ☺️味噌煮込みうどんが名物で行列の出来る人気店の老舗麺処！こだわり素材で地元民に愛されているうどんとそばのお店！大海老天はサクサクの衣に海老がとにかく大きくて食べ応えがある🍤うどんは弾力のある麺のもっちりした食感と手打ちならではのコシ出汁も美味しかった！サクサクの天ぷらと絶品の手打ちうどんを食べに是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市日置江1-110-1',
detail_holiday:'火曜日',
detail_hours:'11:00-15:00 17:00-21:00',
detail_parking:'約50台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DO5ZVJ8gVNn/?igsh=M29uMnp2b2x0cG1k',
detail_map:'https://maps.app.goo.gl/uspt4PZ8beKdYYFGA',
},
{
store_no:"011",
name:"ノーブルオブザ",
key:['バーベキュー',],
place:'岐阜市',
commnet:'岐阜城を眺めながら手ぶらでBBQ！',
detail_img:1,
detail_text:"金華山と岐阜城の景色を眺めながら手ぶらでBBQを楽しめる『ノーブルオブザ』に行ってきたよ🥩\n岐阜県長良の老舗料理屋で 1969年（昭和44年）に開業したお店🍖金華山と岐阜城の夜景を眺めながら屋外テラスや昭和レトロな雰囲気の店内でA4等級以上の飛騨牛や炉端料理、海鮮料理など厳選された豪華食材でバーベキューが楽しめるよ😊鵜飼開催日には開始を合図する花火が19：45頃に数発あがるからお見逃しなく😌金華山や岐阜城を眺めながら豪華食材でのBBQが手ぶらで楽しめるから是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市長良雄総873-1',
detail_holiday:'無し',
detail_hours:'17:00-22:00',
detail_parking:'約12台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DO1w8xIky4z/?igsh=MWJiY3NiNGo4OGg1cg%3D%3D',
detail_map:'https://maps.app.goo.gl/94VT8uR4mL3vU3RbA',
},
{
store_no:"012",
name:"とんかつ　螢水（けいすい）",
key:['和食',],
place:'岐阜市',
commnet:'炊き立ての土鍋ご飯で食べる超贅沢とんかつ！！',
detail_img:1,
detail_text:"岐阜市加納にある『とんかつ 螢水（けいすい）』に行って来たよ🐷JR岐阜駅南口から徒歩1分🚶ミシュラン掲載店『焼き鳥みずき』がプロデュースの人気とんかつ店！炊き立ての土鍋ご飯で食べる超贅沢とんかつ！！扱ってるブランド豚は贅豚(宮城)、岩中豚(岩手)、オーシャントン(栃木)、ボーノポークぎふ(岐阜)など。まず一口目はクリスマス島の塩で、その後は粉末しょうゆやオリジナルソースで！やっぱりお塩がオススメ🧂メンチカツも肉汁溢れ、肉の旨みもたまんない🤤豚汁とキャベツは1回ずつおかわり無料でボリューム感もGOOD！低温調理なので少し時間が掛かるけど全てレベルが高いのでオススメ☺️何人かで行って食べ比べするのが良さそう！目の前の駐車場は2台のみで個室もあるよ！絶品とんかつを贅沢に炊き立て土鍋ご飯で食べれるから是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市加納栄町通2-14 ',
detail_holiday:'無し',
detail_hours:'11:00-14:30 17:30-21:00',
detail_parking:'約2台　その他は隣接駐車場',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOx_xYGAe5W/?igsh=MTExZzQ3YzE2ZGsyag%3D%3D',
detail_map:'https://maps.app.goo.gl/w3wLYRyJnvJe2jQC7',
},
{
store_no:"001",
name:"花月　えん",
key:['ラーメン',],
place:'羽島市',
commnet:'脂ののった豚バラが美味しい味噌ラーメン！',
detail_img:1,
detail_text:"羽島市にある『花月\nえん』に行ってきたよ🍜ベースの醤油ラーメンが700円とコスパよし、ボリューム満点のラーメン店！アルコールやサイドメニューも豊富で深夜営業してるのが嬉しい☺️ラーメンは脂の乗った豚バラがとろとろで美味しくて、オススメの味噌ラーメンは基本は太麺(変更も可能)味によって麺の太さが違うよ！にんにくチャーハンは大粒のニンニク入りで破壊力抜群🧄オム炒飯は他店にはあまりないメニューで美味しいからオススメだよ！サイドメニューは砂肝、手羽先などがあり居酒屋のようなメニューも豊富で飲む方にもGOOD👍羽島市の一宮大垣線沿いで、少し駐車場が停めにくいので駐車の際は気をつけてね！コスパ、ボリューム共に満足度が高いから是非是非行ってみてね😆",
detail_address:'岐阜県羽島市竹鼻町狐穴422-1',
detail_holiday:'木曜日',
detail_hours:'11:00-14:30 18:00-1:30 17:00-1:30(土・日曜日)',
detail_parking:'約9台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOmXOXQE9XY/?igsh=aG5mZHBsYnVlZTNi',
detail_map:'https://maps.app.goo.gl/uHg2Zr2UkZXVcopo7',
},
{
store_no:"004",
name:"焼肉なか",
key:['焼肉','和食',],
place:'各務原市',
commnet:'美味しいお肉がコスパよく食べれる焼肉屋さん！',
detail_img:1,
detail_text:"各務原市にある『焼肉なか』に行って来たよ🥩各務原市内に2店舗あって美味しいお肉がコスパ良く食べれるよ☺️おすすめはタン塩🧂厚切りで脂がのっていて食べ応え有り！和牛ひれ肉は柔らかくて上質なお肉！牛ホルモンはぷりぷりな脂でとってもおすすめだよ😋醤油ベースの焼肉ダレはご飯との相性も抜群！！美味しいのに土曜日来店でも混んでない所も良かったよ！上質なお肉をお値打ちに食べたくなったら是非是非行ってみてね😊",
detail_address:'岐阜県各務原市鵜沼三ツ池町2-148',
detail_holiday:'火曜日',
detail_hours:'17:00-22:00',
detail_parking:'約11台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOiJjfJgZGB/?igsh=bXgyMW00MzhwcGNh',
detail_map:'https://maps.app.goo.gl/6m8FKhDiRbwuYgx97',
},
{
store_no:"004",
name:"麺屋一幸",
key:['ラーメン',],
place:'岐南町',
commnet:'鶏泡スープが麺に絡んで美味しい！',
detail_img:1,
detail_text:"羽島郡岐南町にあるラーメン店『麺屋一幸』に行ってきたよリピートで5回目の来店です😂鶏泡白湯塩ラーメンは真っ白なエスプーマ！鶏泡スープが麺に絡んで美味しい😋期間限定とうもろこしの冷製ラーメンはカレーミンチで味変が楽しめて具材をバゲットにのせて食べることもできる🥖お店インスタかXのフォロー画面提示でトッピングが1品無料だよ！リピート間違いなしのラーメン店へ是非是非行ってみてね☺️",
detail_address:'岐阜県羽島郡岐南町上印食6-72-1',
detail_holiday:'水曜日',
detail_hours:'11:00-14:00 18:00-20:30',
detail_parking:'約6台',
detail_url_shop:'https://www.instagram.com/gifu_menya_ikkou/',
detail_url_link:'https://www.instagram.com/reel/DOQKgMvgdUP/?igsh=MTJmNzdhb2M4dWV4NQ%3D%3D',
detail_map:'https://maps.app.goo.gl/iebVDLAgxA83ZdJs7',
},
{
store_no:"003",
name:"しゃにむに",
key:['ラーメン',],
place:'本巣市',
commnet:'麺は北海道産小麦100%使用でつるつるの極太麺',
detail_img:1,
detail_text:"本巣市にあるぶっと麺『しゃにむに』に行ってきたよ🍜いつも行列が絶えない人気のラーメン店！麺は北海道産小麦100%使用でつるつるの極太麺超濃厚まぜそばは追い飯が合う🍚なつまぜそばはシャキシャキ野菜とトマトを極太麺に絡ませてさっぱりと美味しくいただけます😋麺の大盛り無料！ランチはおい飯無料！行列覚悟で是非是非行ってみてね😊",
detail_address:'岐阜県本巣市上真桑2224-1',
detail_holiday:'火・水曜日',
detail_hours:'11:00-14:00 18:00-20:45',
detail_parking:'約8台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOARgp5gZ3r/?igsh=MXYwaW83d2dwMnl6aQ%3D%3D',
detail_map:'https://maps.app.goo.gl/eP5HYPLN5aGDvwZq6',
},
{
store_no:"001",
name:"濃厚野菜タンメン　牛しおBASE",
key:['ラーメン',],
place:'瑞穂市',
commnet:'牛肉の乗った塩ベースのタンメンが絶品！',
detail_img:1,
detail_text:"瑞穂市にあるラーメン店『濃厚野菜タンメン 牛しおBASE』に行ってきたよ🍜\n牛肉をトッピングした塩ベースのタンメンが看板メニューのラーメン店！\n巣南ホルモンの系列店で牛と野菜の旨みスープにストレート細麺が絡んで美味しい☺️\nホルモンはぷりっぷりで食べ応えじゅうぶん！牛すじはトロトロでとても柔らかく、さすが焼肉屋さんの系列店だと納得できるおいしさ！\nコノミヤ巣南店の向かい側にあるすなみ十番の一画にあるよ！\nタンメン好きは是非是非行って来てね😊",
detail_address:'岐阜県瑞穂市瑞穂市田之上241-1',
detail_holiday:'月曜日',
detail_hours:'11:00-14:00',
detail_parking:'約8台（共用駐車場多数）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRmBtPWAcUe/?igsh=NmE4cmRxdzJ3a3Zq',
detail_map:'https://maps.app.goo.gl/ehVcXAVZPUgf1Exb7',
},
{
store_no:"001",
name:"Café　じゃりんこ",
key:['カフェ',],
place:'笠松町',
commnet:'コスパ最強モーニングが魅力！',
detail_img:1,
detail_text:"羽島郡にある人気モーニングのお店『CAFEじゃりんこ』に行ってきたよ☕️外観の可愛いワンちゃんの看板が目印🐶ドリンク代だけで楽しめる“コスパ最強モーニング”が魅力のお店！モーニングの種類もとっても豊富で、量はまるでランチ並みだからしっかりお腹いっぱいになれて大満足だよ☺️土日限定のスペシャルカレーや、冬季限定のおでんモーニングなど気になる🤩11時半ラストオーダーだからランチで行っても良さそう！是非是非行ってみてね☺️",
detail_address:'岐阜県羽島郡笠松町中野183',
detail_holiday:'月・火曜日',
detail_hours:'7:00-12:00',
detail_parking:'約13台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRnsalNAYu9/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/Em5XrZPwteQymGjm6',
},
{
store_no:"013",
name:"小塩屋",
key:['和食','ラーメン',],
place:'岐阜市',
commnet:'岐阜市で昔ながらの定食屋といったらここ！',
detail_img:1,
detail_text:"岐阜駅近くの名物大衆食堂『小塩屋』に行ってきたよ岐阜市で昔ながらの定食屋と言ったら、まず出てくるのがここ！！まるで昭和時代にタイムトリップしたかのような温かい雰囲気に包まれた食堂で、平日でもオープン直後から次々とお客さんが入り、すぐ満席になるほどの人気ぶり！どの定食もほぼ1000円以下でリーズナブル！今回のお目当ては名物の 唐揚げ定食！山盛りの唐揚げは衣ふわっ、中はジューシーで「コレコレ」ってなる味😆定食に付いてくる赤だしは150円でラーメン（小）に変更できるからもちろん変更しちゃうよね🤣満腹＆大満足の最強定食です。駐車場は道路を挟んで北側、一方通行なので注意してね。昔ながらの大人気の定食屋さんに是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市菊地町1丁目1',
detail_holiday:'無し',
detail_hours:'11:00-20:00',
detail_parking:'約6台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRxnh53Ewr7/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/4BNcXqTPTF94SuZSA',
},
{
store_no:"014",
name:"りきどう",
key:['和食','ラーメン',],
place:'岐阜市',
commnet:'岐阜ラーメン食べログNo.1!',
detail_img:1,
detail_text:"岐阜県No.1ラーメン店『りきどう』に行って来たよ☺️👑岐阜県ラーメン食べログランキング 1位/771位🍜食べログ評価：3.74🥩百名店選出：2022～2024年3年連続店主さんは、東京の人気店「らぁめん ほりうち」さん、「中華そば すずらん」さん等で修業！自家焙煎小麦を使った“香る麺”や肉汁滴る凄旨豚が楽しめるお店！オススメは他では味わえない凄平麺とこだわりのチャーシュー！トッピングの特大厚切りチャーシューは 5枚入り！ボリューム満点なので覚悟して注文してね💥麺もチャーシューもつけ汁も最高！一度は行くべき名店🍜土曜日1３時訪問で行列8人…待ち時間２０分でまだ早い方だったのかも・・・行列覚悟で是非是非行ってみてね😆",
detail_address:'岐阜県岐阜市島栄町2-53',
detail_holiday:'無し',
detail_hours:'11:00-14:15 17:30-21:15',
detail_parking:'約12台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DR8HvpZk1aY/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/hHVH6YPCiaCuKP167',
},
{
store_no:"015",
name:"韓国食彩オモニ",
key:['韓国',],
place:'岐阜市',
commnet:'プルコギが絶品！',
detail_img:1,
detail_text:"岐阜市川部にある『韓国食彩オモニ』に行ってきたよ🇰🇷プルコギがおすすめのお店！甘辛いタレにたっぷりのお野菜とお肉が絡んで絶品！サンチュにコチュジャンを入れて巻いて食べたら美味しさ倍増！！〆にうどんとチーズをトッピング🧀チヂミは熱々の鉄板にのって提供！カリッともっちり香ばしくて美味しい🤤どの料理も本格韓国料理でお酒も進んじゃう🍺是非是非行ってみてね🥩",
detail_address:'岐阜県岐阜市川部5-60-2',
detail_holiday:'月曜日',
detail_hours:'11:30-14:00 17:00-22:00',
detail_parking:'約10台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DSHncAjAej6/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/Frfw8sTPo7yjbYqw7',
},
{
store_no:"016",
name:"カーポダンノ",
key:['洋食',],
place:'岐阜市',
commnet:'石窯で焼く本格ピッツァが絶品！',
detail_img:1,
detail_text:"本巣郡北方町にある『カーポダンノ』に行ってきたよ🍕\nパスタランチが880円から食べられてコスパ・味・ボリューム最高のお店！石窯で焼く本格ピッツァやパスタがいただけるカジュアルイタリアン☺️\nテイクアウトピザもあるのでホームパーティ様にもおすすめだよ！\n美味しいピザとパスタを食べたい人は是非是非行ってみてね😆",
detail_address:'岐阜県本巣郡北方町平成8-35',
detail_holiday:'無し',
detail_hours:'11:30-15:00 17:30-21:30 (月・水)11:30-15:00',
detail_parking:'約13台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DSLmY9ok__C/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/VBbSyA9rHcuEe7av7',
},
{
store_no:"017",
name:"赤れんが",
key:['洋食',],
place:'岐阜市',
commnet:'食べログ100名店にも選ばれた洋食屋さん！',
detail_img:1,
detail_text:"岐阜市河渡にある洋食屋さん『赤れんが』に行ってきたよ🍽️\n住宅街に佇む洋食屋さんでなんと食べログ百名店に選ばれたお店！\nなんと言ってもハンバーグランチが1000円で食べられるハイコスパ😊\nデミグラスソースのかかったハンバーグが絶品で口の中で溶ける柔らかさ！ジューシーなハンバーグは絶品😋\nサラダは自家製ドレッシングが美味しくてカリッと揚げられたクリームミートコロッケも美味しい！\n自家製メニューも豊富で優しい味わいの大満足ランチだよ！\n味もコスパもいいから食べログ百名店の人気店に是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市河渡3-120-1',
detail_holiday:'木曜日',
detail_hours:'11:30-14:00 17:30-20:30',
detail_parking:'約6台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DSdkXL1k4yQ/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/FrSJT1gQeQQrgZZQA',
},
{
store_no:"018",
name:"チイタ",
key:['カフェ',],
place:'岐阜市',
commnet:'発芽玄米と発酵食品が食べれる人気の隠れ家カフェ！',
detail_img:1,
detail_text:"岐阜市にある発芽玄米が食べられるオーガニックカフェ『チイタ』に行ってきたよ☕️\n発芽玄米と発酵食品が食べれる人気の隠れ家カフェ！身体に優しいメニューで最初に空腹時に飲むとよい酵素ジュースが出てきたよ！\n多品目を少しづつ食べることができるのが嬉しい☺️\n可愛い店内で身体に優しいお料理が食べれるから是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市竜田町3-17',
detail_holiday:'水・日曜日',
detail_hours:'11:00-17:00',
detail_parking:'約5台',
detail_url_shop:'https://www.instagram.com/cafechiita',
detail_url_link:'https://www.instagram.com/reel/DSn_zyekmwM/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/yKN4S6g96gFNHmrc6',
},
{
store_no:"002",
name:"日々のごはん　となり",
key:['カフェ','和食',],
place:'瑞穂市',
commnet:'自家製麹を使った優しい料理！',
detail_img:1,
detail_text:"瑞穂市にある『日々のごはん となり』に行ってきたよ☺️\n5月7日New Openした塩麹や醤油麹、発酵生姜など昔ながらの発酵調味料を使用した体に優しい料理が味わえるお店！\n心がほっとする自家製麹を使った体に優しい料理の数々でどれも素材の持ち味を生かした上品な味付けに癒やされる😌\n心も身体も整う絶品麹ランチを食べに是非是非行ってみてね😊",
detail_address:'岐阜県瑞穂市中宮字江東469-1',
detail_holiday:'月・木・日曜日',
detail_hours:'11:00-14:30',
detail_parking:'約10台',
detail_url_shop:'https://www.instagram.com/hibino_gohan_tonari?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DStIasakibo/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/so8MJRS5gonQzmkVA',
},
{
store_no:"019",
name:"moa-moa かふえ＆だいにんぐ",
key:['カフェ','洋食',],
place:'岐阜市',
commnet:'ボリューム満点の大人様ランチが人気！',
detail_img:1,
detail_text:"岐阜県岐阜市にあるカフェ&ダイニング『moa-moa かふえ＆だいにんぐ』に行ってきたよ☺️\n2024年11月11日オープンしたボリューム満点の大人様ランチが食べられる人気のお店！\nお店は住宅メーカー『シャルドネ』にトータルコーディネートを依頼しているからオシャレな店内と外観だよ！\nハンバーグ・エビフライ・唐揚げがワンプレートにのった、まさに“大人のお子様ランチ”😋\nこぶりでしっかり練られた肉肉しいハンバーグ、身が太くプリプリな大きなエビフライ、サクサク衣でジューシーな唐揚げと、どれもご飯が進む美味しさ！\nご飯は白米と黒米の2種類があり、おかわり自由（大中小が選べる）なので、おかずが余っても大丈夫🙆\nお子様ランチはないけど、ご飯おかわり自由で、おかずもボリューム満点だから子供とシャアして食べるのにもちょうどいい☺️\n人気店なので複数人で行くなら予約必須！\n店内は明るくお洒落な空間で、テーブルや席の間隔が広くとってあるからゆったり過ごせるよ！\n是非是非行ってみてね☺️",
detail_address:'岐阜県岐阜市領下1666',
detail_holiday:'水・日曜日',
detail_hours:'11:30-16:00(月・火・木)11:30-16:00 18:00-22:00(金・土)',
detail_parking:'約5台',
detail_url_shop:'https://www.instagram.com/moa_moa_cafe?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DS1AfaKgc0K/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/WkAGU9DeSqxtU2UL7',
},
{
store_no:"003",
name:"マルサ水産",
key:['和食','海鮮',],
place:'瑞穂市',
commnet:'産地直送にこだたった新鮮な魚が美味！',
detail_img:1,
detail_text:"瑞穂市にある『マルサ水産』に行ってきたよ🐟\n2025年10月8日にNew Openの海鮮和食レストラン！\n平日は日替わりランチ他のメニューが豊富で海鮮丼、天丼、お刺身定食、煮魚、焼き魚等の定食があるよ！\nご飯、味噌汁コーヒーのおかわり無料なのが魅力☺️\nその地域に行かないと食べることができない魚介類等の食材を新鮮なまま食べれる「産地直送」にこだわっていて新鮮かつ質の高い鮮魚が食べれるよ！\n夜はお魚に合う厳選した日本酒もあって居酒屋としても利用できるから是非是非行ってみてね😊",
detail_address:'岐阜県瑞穂市穂積1517-2',
detail_holiday:'無し',
detail_hours:'11:00-15:00 17:00-22:00',
detail_parking:'約32台',
detail_url_shop:'https://www.instagram.com/marusa_hozumiten?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DTNP92vExJN/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/vyeWYNPNbQ4ieKBA7',
},
{
store_no:"020",
name:"まさと",
key:['和食','蕎麦','ラーメン','味噌カツ',],
place:'岐阜市',
commnet:'定食の数がとにかく豊富でどれもボリュームが凄い！',
detail_img:1,
detail_text:"岐阜市六条にあるお食事処『まさと』に行ってきたよ☺️\n定食の数がとにかく豊富でどれもボリュームが凄い！\n日替わりランチは980円でエビフライ、手作りメンチカツ、漬物、ライス（小）、かけそば、コーヒーまで付いてくる！\n駐車場は目の前と少し離れたところにあるよ！\nコスパ、ボリューム満点定食を食べに是非是非行ってみてね😊",
detail_address:'岐阜県岐阜市六条大溝3-8-16',
detail_holiday:'日曜日',
detail_hours:'11:30-14:00 17:30-20:00',
detail_parking:'約9台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DTSUmWRgVyt/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/4F2Z9GQkWQTBi9Kq9',
},
{
store_no:"021",
name:"吉野家",
key:['和食','牛丼',],
place:'岐阜市',
commnet:'牛丼と言えばこのお店！',
detail_img:1,
detail_text:"日本全国に約1,273店舗展開（2025年12月末現在）する牛丼チェーン店『吉野家』に行ってきたよ☺️\n2026年1月6日〜数量限定の新作登場🔥\nその名も『厚切り豚角煮定食』（税込1,152円）\n見た瞬間びっくりするレベルの分厚さ😳\nなのに箸でホロホロ崩れるほど柔らかい…！\n甘辛で濃厚なタレがしっかり染みてて、タレだけでご飯一杯いけるレベル🍚✨\n昨年大人気だったのも納得のクオリティ！数量限定で売り切れの可能性あり⚠️\n気になってる人はお早めに！\n前回食べ逃した人も今回はぜひ🤤\n是非是非行ってみてね☺️",
detail_address:' 岐阜県岐阜市六条江東３丁目５－１',
detail_holiday:'無し',
detail_hours:'4:00-2:00',
detail_parking:'約20台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DTWVpdHE-6w/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/ZudZ9H5rXXnSmWh78',
},
{
store_no:"001",
name:"焼肉よっちゃん",
key:['和食','焼肉',],
place:'大垣市',
commnet:'激うまの牛タンが最高！',
detail_img:3,
detail_text:"岐阜県大垣市にある人気焼肉店『焼肉 よっちゃん 築捨店』に行ってきたよ🥩\n厚切り上塩たんは極厚なのにめちゃくちゃ柔らかい！！外はしっかり焼いたら香ばしく、内側はジューシーで柔らかい！噛むたびに肉の旨味が口の中に広がり、牛タン特有のしっかりとした歯ごたえが楽しめる！レモンとネギ塩で味わうのが最高！普段は牛タンでご飯は食べれない派なんだけど、ココのは牛タンだと食べれちゃう！どの肉も美味しくて、タンユッケなどお刺身の種類も豊富！落ち着いた雰囲気の店内でメニューが豊富！\n飲み放題やコースも税込3000円〜あるから忘年会にも最適だよ！肉質がいいのに、コスパ最高！！人気店なので予約必須！！行ったら先ずは厚切り上塩タンとねぎ上塩タンを頼んでみて！\n激ウマの牛タンを食べに是非是非行ってみてね☺️",
detail_address:'〒503-0854 岐阜県大垣市築捨町３丁目１４−１４',
detail_holiday:'月曜日',
detail_hours:'17:00 - 00:00',
detail_parking:'約14台',
detail_url_shop:'https://www.instagram.com/yakiniku.yottyan.honten?igsh=MTNzOTc5cGJieXVxcw==',
detail_url_link:'https://www.instagram.com/reel/DRD5YAPAVlO/?igsh=MTVtbXgwN2tkZ21hOQ==',
detail_map:'https://maps.app.goo.gl/1ACQbjcJzfuTuctc7',
},
{
store_no:"002",
name:"ノンダリスタンド",
key:['カフェ',],
place:'大垣市',
commnet:'鉄工所の中にあるカフェ！',
detail_img:1,
detail_text:"大垣の佐久間工業の敷地内にあるカフェ『ノンダリスタンド』に行ってきたよ☕️2025年8月にオープンした鉄工所の中にあるカフェでパイやタコス、ドリンクがあるよ🌮シンプルな店内にはカウンターとテーブル席があってコーヒーはハンドドリップで淹れてくれるよ！敷地内にはオシャレなインテリア雑貨などを販売する「SIKAKU」があって知る人ぞ知るスポット！",
detail_address:'岐阜県大垣市青柳町1-243',
detail_holiday:'火・木曜日',
detail_hours:'月・水・金　13:00-18:00　土・日　11:00-18:00',
detail_parking:'約5台',
detail_url_shop:'https://www.instagram.com/nondaristand/',
detail_url_link:'https://www.instagram.com/reel/DRB5Va3Af1g/?igsh=NjU0dHM5c20zZDZ1',
detail_map:'https://maps.app.goo.gl/XQ6BT6pd9RSRJM9u6',
},
{
store_no:"003",
name:"マシマシカーニバル",
key:['ラーメン',],
place:'大垣市',
commnet:'二郎好きの方必見！',
detail_img:1,
detail_text:"二郎系好きの皆さまお待たせしました！インパクト絶大のラーメンがついに大垣で味わえる🍜極太麺に醤油ベーススープで具材はホロホロの特大チャーシューに野菜マシマシは600グラムと圧倒的なボリューム！！個人的には背脂少なめがオススメ！ニンニクは大事な用事がない時に😆二郎系で独立した店主は常に試行錯誤をしながら最高の二郎系を作り上げていく意気込み✊圧倒的なボリュームの二郎系ラーメンを食べに是非是非行ってみてね😊",
detail_address:'岐阜県大垣市加賀野5丁目1-4',
detail_holiday:'水曜日',
detail_hours:'11:00-15:00 17:00-21:00',
detail_parking:'約14台',
detail_url_shop:'https://www.instagram.com/mashimashicarnival?igsh=dW9mMWl6b3JmazFw',
detail_url_link:'https://www.instagram.com/reel/DPpWkpjkyuw/?igsh=Y21uaGR3eGNvbjB5',
detail_map:'https://maps.app.goo.gl/ZQmbbQFE8j1RZHXf6',
},
{
store_no:"001",
name:"Yo-shoku　OKADA",
key:['洋食',],
place:'揖斐川町',
commnet:'人生を味わうこだわりの洋食屋さん！',
detail_img:1,
detail_text:"揖斐郡大野町にある『Yo-shoku OKADA』に行ってきたよ🍝\n フレンチレストランで修行したシェフが作るお店🧑‍🍳食べログ『洋食百名店EAST 2025』に選ばれた人生を味わうごだわりの洋食屋さんだよ！ \n火曜日夜は『〇火ラー』の日でこだわりのラーメンが食べられるよ🍜是非是非行ってみてね☺️",
detail_address:'岐阜県揖斐郡大野町下磯屋敷前521-2',
detail_holiday:'木曜日',
detail_hours:'11:00-14:00 18:00-21:00',
detail_parking:'約17台（共用駐車場)',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DSOYR7cgcGV/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/JyP1AnMkvpW82nvk6',
},
{
store_no:"001",
name:"豊まる",
key:['和食','串揚げ',],
place:'海津市',
commnet:'肉厚で衣が薄く激うま串かつ！',
detail_img:3,
detail_text:"岐阜県海津市のお千代保稲荷参道にある串揚げをメインにした食事処『豊まる』に行ってきたよ☺️\n商売繁盛祈願のお千代保稲荷さん参拝とセットや初詣のついでにも、ふらっと食べ歩きにも◎おちょぼ稲荷に行ったら、まずはここ！！おすすめのお店だよ☺️\n▶︎名物 串かつ 絶品牛すじどて煮 他にも丼物、麺類などを提供していて、串かつは、肉厚で衣は薄く激うま！\n▶︎牛すじは国産の黒毛和牛を使用！\n▶︎ 2015年11月25日オープンから10周年を迎えた人気店！\n▶︎ テーブルにある紙に手書きで注文するスタイル！\n▶︎ 揚げたては立ち食べも美味しいけど、やっぱり座りたくなる！店内は席数が多く座ってゆっくり食べられるのが嬉しい！\n絶品串カツを食べに是非是非行ってみてね☺️",
detail_address:'岐阜県海津市平田町三郷字村1851-4',
detail_holiday:'無し',
detail_hours:'10:00-17:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:'https://www.instagram.com/toyomaru.ochobosan?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DTCKUUfASAA/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/7PKQQDiKu615XP1Q8',
},
{
store_no:"001",
name:"よいひ",
key:['和食','蕎麦','豚足','鍋',],
place:'犬山市',
commnet:'寒い季節にピッタリの美味しい鍋が食べれるお店！',
detail_img:5,
detail_text:"愛知県犬山市に 2025年1月にOpenしたそばと豚足となべの店『よいひ』に行って来たよ☺️\n寒い季節にピッタリの美味しい鍋が食べれるお店！\n『鮭とホルモンとせせりの鉄板ピリ辛スタミナ味噌鍋』は山盛りのもやし・玉ねぎ・キャベツ・にんじんの上に鮭・せせり・ホルモン・キムチがのっていて見た目の迫力もすごい！\nピリ辛の鍋はビールとの相性も抜群で自分好みのトッピングが可能！\n〆の全粒粉入りうどんはモチモチ食感で、鍋の旨みを最後まで堪能できる！鍋のスープに使われてる粕味噌にはビタミンB群が豊富で、アンチエイジングや腸活にもぴったり！\n名物豚足はぷるっぷるでクセも臭みもなくコラーゲンたっぷりだから肌もツヤツヤ間違いなし！\n朝8時〜10時30分、14時30分〜17時は飲み物だけの利用もOKでモーニングからディナーまで幅広く利用できるのが魅力☕️\nピリ辛でボリューム満点のスタミナ鍋を食べに是非是非行ってみてね😊",
detail_address:'愛知県犬山市羽黒新田郷東11-2',
detail_holiday:'無し',
detail_hours:'8:00-21:30',
detail_parking:'約10台',
detail_url_shop:'https://www.instagram.com/soba.tonsoku.nabe.yoihi/',
detail_url_link:'https://www.instagram.com/reel/DQvbM6dgQaQ/?igsh=bm10N2hwaDFwdXh6',
detail_map:'https://maps.app.goo.gl/BeEkeCqAmFsVi2kP7',
},
{
store_no:"001",
name:"CROCE & Co.",
key:['モーニング',],
place:'一宮市',
commnet:'サイコロ食パンがふわふわで美味しい！',
detail_img:1,
detail_text:"愛知県一宮市にある人気カフェ『CROCE ＆ Co.』に行ってきたよ☕️サイコロ食パンが有名なお店🍞食パンは焼きたてフワフワでほんのり甘い生地が美味しい😋モーニングは7時から11時までやってて、パンは生サイコロ食パンか手乗りベーグルが選べるよ！スペシャルプレートは食パンの他にサラダ、ハムに、タマゴ、コーンスープ、オレンジ、フライなどが付いてきて超豪華！他にもモーニングメニューが豊富！パンやドーナツのテイクアウトもできるよ！贅沢なモーニングを味わいに是非是非行ってみてね☺️",
detail_address:'愛知県一宮市開明教堂池41-1',
detail_holiday:'無し',
detail_hours:'7:00-17:30',
detail_parking:'約30台',
detail_url_shop:'https://www.instagram.com/cafe_croce/',
detail_url_link:'https://www.instagram.com/reel/DQh8REfEyF4/?igsh=MXJoYzA1emxsenZ4cg%3D%3D',
detail_map:'https://maps.app.goo.gl/bYRkjVBjdf8KKeUw5',
},
{
store_no:"001",
name:"アランチャ",
key:['洋食',],
place:'名古屋市',
commnet:'絶品オムライス！',
detail_img:1,
detail_text:"名古屋市西区にある洋食屋さん『アランチャ』に行ってきたよ🐥日曜日はパチンコシェフの作る創作料理の数々！うずらひよこのトッピングが可愛いけどのにし忘れて悔しい😭メニューは100種類ほどあってどれもシェフのアイディアが沢山詰まってるよ！オムライスはどれも絶品でふわトロたまごとソースが美味しくてたまらない😋ひよこうずらトッピングは6個で380円だよ🐥見た目だけじゃなく味も美味しいから是非是非行ってみてね！",
detail_address:'愛知県名古屋市西区那古野1-11-10',
detail_holiday:'日曜日',
detail_hours:'11:30-14:00 17:30-22:30',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:'https://www.instagram.com/arancia.en/',
detail_url_link:'https://www.instagram.com/reel/DQd21f6gb_G/?igsh=MWFya3FjbHR1aW9obQ%3D%3D',
detail_map:'https://maps.app.goo.gl/4s59UAxajdxsMW1n6',
},
{
store_no:"002",
name:"BEN'S  MORNING CAFÉ",
key:['カフェ','モーニング',],
place:'一宮市',
commnet:'10種類以上のモーニングと国産小麦のドーナツが楽しめる！',
detail_img:1,
detail_text:"一宮市にある人気のカフェ『BEN'S MORNING CAFE』に行ってきたよ☺️10種類以上のモーニングと国産小麦のドーナツが楽しめるオシャレで人気のカフェ！オススメはモーニングで7:30～11:45までに注文できれば食べれるよ！※11時45分以降はランチメニューに切り替わるから注意してね⚠️人気のクロックマダムはカリッと焼かれた厚切りトーストにチーズたっぷり、卵と生ハムの塩気がたまらない！3段重ねのボリュームたっぷりのパンケーキはフワフワ生地に生クリームとメープルをかけて食べれば至福のひととき🥞トッピングの種類が豊富なのも魅力的😆昼はランチメニューも豊富でドーナツはお持ち帰りもできるよ！お洒落な雰囲気でちょっと贅沢なモーニングを味わいに是非是非行ってみてね☺️",
detail_address:'愛知県一宮市木曽川町里小牧西川田109',
detail_holiday:'無し',
detail_hours:'6:30-17:00',
detail_parking:'約8台',
detail_url_shop:'https://www.instagram.com/bens_morning_cafe/',
detail_url_link:'https://www.instagram.com/reel/DQP5--CE2HD/?igsh=MWYyZDEwMjN3Y3J3Zw%3D%3D',
detail_map:'https://maps.app.goo.gl/kJpQLTZBgs8uYsye9',
},
{
store_no:"003",
name:"川味菜館",
key:['中華',],
place:'一宮市',
commnet:'早い！安い！うまい！ボリューム満点！',
detail_img:1,
detail_text:"愛知県一宮市にある『川味菜館』に行ってきたよ🍜早い！安い！うまい！ボリューム満点で町中華を手軽に食べたいならココ！メニューが豊富で店員さんの接客も良くて、いつも賑わってるお店だよ☺️コスパ良し！ボリューム満点の町中華を食べに是非是非行ってみてね😆",
detail_address:'愛知県一宮市起字東茜屋6',
detail_holiday:'水曜日',
detail_hours:'11:00-14:00 17:00-00:00',
detail_parking:'約15台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOftkmNATUS/?igsh=dW5zc2F5amJkOWcy',
detail_map:'https://maps.app.goo.gl/jid879BjkhYcEues9',
},
{
store_no:"002",
name:"焼肉＆手打ち冷麺二郎(柳橋店)",
key:['焼肉','ラーメン',],
place:'名古屋市',
commnet:'お肉はどれも新鮮で名物の冷麺がおすすめ！',
detail_img:1,
detail_text:"名駅柳橋にある焼肉&手打ち冷麺二郎に行ってきたよ🥩某テレビ番組で焼肉通の寺門ジモンを参りましたと言わしめた数少ないお店！！店内はおしゃれで落ち着いた広々とした空間！お肉はどれも新鮮で二郎名物の冷麺がおすすめ！すだちととろろ昆布と梅干しが乗った冷麺はツルツルの麺と出汁が美味しくさっぱりと食べれるよ☺️名駅から徒歩5分の好立地！人気店だから予約して是非是非行ってみてね😆",
detail_address:'愛知県名古屋市中村区名駅4-14-10 柳橋Food Market 3F',
detail_holiday:'無し',
detail_hours:'11:00-15:00 17:00-23:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DONzj7egdLi/?igsh=bTF0bHN4emdlcjEx',
detail_map:'https://maps.app.goo.gl/dj8xHdHc6G8f9tWy9',
},
{
store_no:"004",
name:"かに屋",
key:['和食','うどん',],
place:'一宮市',
commnet:'一宮で味噌煮込みうどんと言えばここ！',
detail_img:1,
detail_text:"【創業55年の老舗】一宮で味噌煮込みうどんと言えばここ！\n無塩の多加水・高熟成手打ち麺は、しっかりしたコシと小麦の香りが絶妙。数種類ブレンドされた八丁味噌の深い味わいに、天ぷら（大海老、さつまいも、ピーマン、かまぼこ）と卵トッピングが絡んで、幸せな美味しさが広がります☺️寒い時期は特に行列必至だけど、並ぶ価値あり！開店30分前に店前に記名簿が出されて、電話予約もできるよ！\n数種類ブレンドした八丁味噌と腰があるうどんがめちゃくちゃ美味しいから是非是非行ってみてね☺️",
detail_address:'一宮市別明町3丁目11-1',
detail_holiday:'水曜日',
detail_hours:'11:00-14:30 17:00-22:00',
detail_parking:'約20台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRqVcBUAbXE/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/kTjJGM6Pw2v8UUaT8',
},
{
store_no:"005",
name:"ぐり虎食堂",
key:['和食','ラーメン',],
place:'一宮市',
commnet:'厳選食材を使った一杯！！',
detail_img:2,
detail_text:"一宮駅の「イチ＊ビル」の中にできた人気ラーメン店『ぐり虎食堂』に行ってきたよ🍜2021年ミシュランガイド掲載人気店「麺処ぐり虎」の系列店がついに一宮にオープン🍜\n本店の想いを受け継ぎ、国産鶏や瀬戸内の魚、昆布・鰹節など厳選食材を使った一杯が楽しめる！\n鶏8時間・豚骨13時間じっくり煮込んだスープは塩ラーメンで堪能でき、毎朝打つ自家製麺のつけ麺もおすすめ！\n明るいカフェのような店内だから女性ひとりでも入りやすいのも魅力🤩\n卓上の玉子と海苔は食べ放題だからラーメンにも丼にも入れ放題で幸せ☺️\nぐり虎名物の特製鶏塩ラーメンは、あっさりながら柚子の香りが広がる旨みたっぷりの一杯！\n黒毛和牛の焼きすきごはんは、玉子との相性が抜群で、贅沢ながらもぺろっと食べられちゃう！\n特製豚骨魚介つけ麺は、極太麺と魚介の香りが楽しめる一品で、つけ汁は固形燃料で温められているから最後まで熱々で味わえる🔥\n一宮店限定の熟成赤辛醤油ラーメンは、辛いのが好きな人におすすめ！玉子を入れるとマイルドになり、さらに食べやすくなるよ！\n是非是非行ってみてね☺️",
detail_address:'愛知県一宮市新生1-1イチ*ビルB1',
detail_holiday:'無し',
detail_hours:'11:00-22:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DSgbDQ1AQ0W/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/6XWt2PXwWn3UMbV46',
},
{
store_no:"001",
name:"giraffe",
key:['カフェ','クレープ',],
place:'稲沢市',
commnet:'ふわっふわで軽い口溶け！',
detail_img:1,
detail_text:"稲沢市にある究極の生クリームクレープ専門店 『giraffe』に行ってきたよ😊\n生クリームの破壊力がとにかく半端ない！北海道産乳を100%使用した生クリームを使用！\n飽きのこない味わいで『コク』と『うま味』を感じられる生クリームは、ふわっふわで軽いくちどけだよ！\n生地もサクッモチッに焼き上げられてクレープ好きにはたまらない😆\n駐車場は店の前に２台スペースがあるけど駐車しにくいから気をつけてね！\nウェットティッシュ持参がおすすめだよ！\n究極の生クリームクレープを食べに是非是非行ってみてね☺️",
detail_address:'愛知県稲沢市松下2-22-2',
detail_holiday:'無し',
detail_hours:'11:00-18:00',
detail_parking:'2台',
detail_url_shop:'https://www.instagram.com/crepe_kyukyoku_inazawa?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DPFTSvUk9c2/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/75XKbfvqxczRVyQR6',
},
{
store_no:"001",
name:"肉匠かどや 食堂spoon",
key:['洋食',],
place:'新城市',
commnet:'お肉屋さんが作る肉料理が絶品！',
detail_img:1,
detail_text:"奥三河の古民家洋食屋さん『肉匠かどや 食堂spoon』に行ってきたよ🥩\n肉匠かどやというお肉屋さんが経営している食堂で鳳来町の古民家を改装したお店の外観は懐かしさを感じる造りでおしゃれ☺️\n流石お肉屋さんの食堂だけあって、どのメニューも肉の厚みがかなりあってど迫力のボリューム🍖\nお肉は柔らかくて脂っこくないから食べやすいよ！\n席は座敷とテーブル席の2種類あり座敷のイスは座布団にも変更できるよ！\nテイクアウト専用のお弁当メニューもたくさんの種類があってサイドメニューの惣菜や揚げ物の購入可能！\n予算や人数に合わせてオードブルも作ってもらえるよ！\nお弁やオードブル等は予約可能なので前もって予約しておくとスムーズ（予約電話→0536-34-0100）\nおすすめなので是非是非行ってみてね😆",
detail_address:'愛知県新城市上吉田字松沢42',
detail_holiday:'月・火曜日',
detail_hours:'11:30-14:30',
detail_parking:'約6台',
detail_url_shop:'https://www.instagram.com/okumikawa_houraikadoya?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DR4DjtygarH/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/83BGazLMYW3uESsBA',
},
{
store_no:"001",
name:"灯台茶屋",
key:['洋食',],
place:'田原市',
commnet:'大アサリと岩牡蠣がとにかく大きい!',
detail_img:1,
detail_text:"愛知県田原市にある『灯台茶屋』に行ってきたよ🏖️\nお店の外で焼く大アサリと岩牡蠣の匂いにつられて来店！\n大アサリと岩牡蠣がとにかく大きい‼︎\n生牡蠣は口に入れた瞬間磯の香りが広がって甘い😋\n大好きな牡蠣をペロリいただきました🦪\n店の外は海が見渡せるシュチュエーションで開放感最高！牡蠣はその場で開いてくれるよ🦪\n幸せの鐘（恋人の生地）に行ったら是非行ってみてね😊",
detail_address:'愛知県田原市伊良湖町古山2814-4',
detail_holiday:'木曜日',
detail_hours:'10:30-15:00',
detail_parking:'50台以上（共通駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DRS1synky1Q/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/rVVtAUWZFyMC2Rzg8',
},
{
store_no:"002",
name:"CINQ MINUTES",
key:['カフェ','クレープ',],
place:'稲沢市',
commnet:'究極の生クリームクレープ!',
detail_img:1,
detail_text:"稲沢市にある究極の生クリームクレープ専門店 『CINQ MINUTES』に行ってきたよ☺️\n2025年11月続々New Open‼︎\n究極の生クリームクレープ\n生クリームの破壊力がとにかく半端ない！\n北海道産乳を100%使用した生クリームを使用！\n飽きのこない味わいで『コク』と『うま味』を感じられる生クリームは、ふわっふわで軽いくちどけだよ！\n生地もサクッモチッに焼き上げられてクレープ好きにはたまらない😆\n駐車場は店の前に２台スペースがあるけど駐車しにくいから気をつけてね！\nウェットティッシュ持参がおすすめだよ！\n究極の生クリームクレープを食べに是非是非行ってみてね☺️",
detail_address:'愛知県稲沢市松下2-22-2',
detail_holiday:'無し',
detail_hours:'11:00-18:00',
detail_parking:'約2台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DQ9IOgdAbyl/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/iRxy51DNUzrrg77U8',
},
{
store_no:"001",
name:"so good coffee & bake",
key:['カフェ',],
place:'豊橋市',
commnet:'行列が絶えない人気のタルトケーキのお店！',
detail_img:1,
detail_text:"愛知県豊橋市にあるカフェ『so good coffee & bake』に行ってきたよ☺️\n行列が絶えない人気のタルトケーキのお店！\n店内もオシャレでタルトの種類が豊富！タルトは甘さ控えめで見た目も味も最高だよ😋\nドリップコーヒーも豆の種類が豊富でコーヒー、ケーキ共に楽しめるよ☕️\n店内でもテイクアウトも出来るので人気店のタルト是非是非行ってみてね😆",
detail_address:'愛知県豊橋市西羽田町202',
detail_holiday:'月・火曜日',
detail_hours:'10:00-18:00',
detail_parking:'約17台',
detail_url_shop:'https://www.instagram.com/sogoodcoffee_andbake?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==',
detail_url_link:'https://www.instagram.com/reel/DP5x3JKgT2z/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/muptfdQWUddo358y9',
},
{
store_no:"002",
name:"Bali CAFE 42",
key:['カフェ',],
place:'田原市',
commnet:'バリに居るような空間のお洒落カフェ!',
detail_img:1,
detail_text:"愛知県田原市にある『Bali CAFE 42』に行って来たよ🌺\nバリに居るような空間のお洒落カフェ☕️\n店内はショールームにもなっていてリゾート気分全開！\nお料理にはチリソースなどかけ放題！\nリゾート気分でくつろぎたい人は是非是非行ってみてね🏝️",
detail_address:'愛知県田原市若見町社宮司40-1',
detail_holiday:'木曜日',
detail_hours:'10:00-16:00(月・火・水・金) 9:00-17:00(土) 9:00-16:00(日)',
detail_parking:'約10台',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DOzFDwvE3pk/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/ejxPbYXV56CqTymk8',
},
{
store_no:"003",
name:"麺家 獅子丸",
key:['ラーメン',],
place:'名古屋市',
commnet:'「洋」をコンセプトに旬素材を活かしたラーメン！',
detail_img:1,
detail_text:"JR名古屋駅太閤通口から徒歩4分の大人気ラーメン店『麺家\n獅子丸』に行って来たよ🍜\n「洋」をコンセプトに、旬素材を活かしたラーメン！\nエスプーマされた濃厚ぱいたんらぁめんが人気で豚骨と鶏ガラをベースにした濃厚スープが特徴だよ😊\nスープを泡立たせてることで、自家製麺と良く絡むから美味しい！\n平日でも行列が出来る人気店でJR名古屋駅から新幹線の高架下沿いを歩いて行くと到着！！\n行列の先にある至福の一杯を是非是非味わってみてね🍜",
detail_address:'愛知県名古屋市中村区亀島2-1-1',
detail_holiday:'無し',
detail_hours:'11:00-14:30 17:00-21:00',
detail_parking:'無し（隣接駐車場）',
detail_url_shop:' ',
detail_url_link:'https://www.instagram.com/reel/DTY5w8_kn59/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
detail_map:'https://maps.app.goo.gl/V3f3c477SV1Z5NYBA',
},
];